level_five/learning_users/basic_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'basic_app'

urlpatterns = [
    # url 'name' parameter is used within HTML when we user,
    # for example {% url 'basic_app:user_login' %}
    url(regex=r'^logout', view=views.user_logout, name='user_logout'),
    url(regex=r'^login/', view=views.user_login, name='user_login'),
    url(regex=r'^register/', view=views.register, name='register'),

]

level_five/learning_users/learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(regex=r'^admin/', view=admin.site.urls),
    url(regex=r'^basic_app/', view=include('basic_app.urls')),
    url(regex=r'^$', view=views.index, name='index'),
]

level_five/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

# Additional information that the User class from Django does not have built in
class UserProfileInfo(models.Model):
    # One to one corresondence with each User
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional fields

    # A user may have a website showcasing her/his portfolio. It may also be blank (no website URL provided)
    portfolio_site = models.URLField(blank=True)

    # Profile picture: Store in subfolder called 'profile_pics' under the 'media' directory
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self) -> str:
        return self.user.username

level_five/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

level_five/learning_users/basic_app/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from basic_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    return render(request=request, template_name="basic_app/index.html")


def register(request: HttpRequest) -> HttpResponse:
    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            # Hash the password using 'set_password' method
            user.set_password(user.password)

            # Save the model to DB
            user.save()

            # Save profile form without committing
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            context = {
                'error_message': 'There seems to be an error in the form you filled. Please retry'
            }
            print(user_form.errors)
            print(profile_form.errors)
            return render(request=request, template_name='basic_app/registration.html', context=context)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = {
        'registered': registered,
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request=request, template_name='basic_app/registration.html', context=context)


@login_required  # Login is required first for a user to be logged out
def user_logout(request: HttpRequest) -> HttpResponse:
    logout(request=request)
    return HttpResponseRedirect(redirect_to=reverse('index'))


def user_login(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        username = request.POST.get(key='username')
        password = request.POST.get(key='password')

        # Authenticate user
        user = authenticate(username=username, password=password)

        if user:
            # Check if user is active
            if user.is_active:
                # Login user
                login(request=request, user=user)
                return HttpResponseRedirect(redirect_to=reverse('index'))

    return render(request=request, template_name='basic_app/login.html')

level_five/learning_users/templates/basic_app/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Basic App</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">Basic App</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index'  %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'basic_app:user_logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
            {% endif %}
        </ul>

    </div>

</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}

</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

level_five/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Django level five</h1>

    </div>
{% endblock %}

level_five/learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter username" id="username">

        <label for="password">Password</label>
        <input type="password" name="password" id="password">

        <input type="submit" name="" value="Login">

    </form>

</div>
{% endblock %}

level_five/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}

    {% if error_message %}
        <h3>ERROR: {{ error_message }}</h3>
    {% endif %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Fill out the form:</h3>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">

            </form>

        {% endif %}

    </div>

{% endblock %}