level_four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from . import views

# Template tagging
app_name = 'basic_app'

urlpatterns = [
    url(regex=r'^other/$', view=views.other, name='other'),
    url(regex=r'^relative/$', view=views.relative, name='relative'),
    url(regex=r'^$', view=views.index, name='index'),
]

level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(regex=r'^basic_app/', view=include('basic_app.urls'))
]

level_four/learning_templates/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    context = {
        'text': 'hello world!',
        'number': 1234,
    }
    return render(request=request, template_name='basic_app/index.html', context=context)


def other(request: HttpRequest) -> HttpResponse:
    context = {

    }
    return render(request=request, template_name='basic_app/other.html', context=context)


def relative(request: HttpRequest) -> HttpResponse:
    context = {

    }
    return render(request=request, template_name='basic_app/relative_url_templates.html', context=context)

level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Basic App</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="#">BRAND</a></li>
                <li><a class="navbar-link" href="#">Admin</a></li>
                <li><a class="navbar-link" href="#">Other</a></li>

            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}

    </div>

</body>
</html>

level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Index</h1>
    <p>{{ number | add:"99000000" }}</p>
    <p>{{ text | upper }}</p>
<p> </p>
{% endblock %}

level_four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Other</h1>
{% endblock %}

level_four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic App</title>
</head>
<body>
<h1>Relative URL templates</h1>
<a href="{% url 'basic_app:other' %}">Other</a>
<a href="{% url 'basic_app:relative' %}">Relative</a>
<a href="{% url 'basic_app:index' %}">Index</a>
<a href="{% url 'admin:index' %}">Admin</a>
</body>
</html>