advanced_section/class_based_views/basic_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'basic_app'

urlpatterns = [
    url(regex=r'^$', view=views.IndexView.as_view()),
    url(regex=r'^school_list/(?P<pk>[-\w]+)$', view=views.SchoolDetailView.as_view(), name='school_detail'),
    url(regex=r'^school_list/$', view=views.SchoolListView.as_view(), name='school_list'),
    url(regex=r'^school_create/$', view=views.SchoolCreateView.as_view(), name='school_create'),
    url(regex=r'^school_update/(?P<pk>[-\w]+)$', view=views.SchoolUpdateView.as_view(), name='school_update'),
    url(regex=r'^school_delete/(?P<pk>[-\w]+)$', view=views.SchoolDeleteView.as_view(), name='school_delete'),
]

advanced_section/class_based_views/class_based_views/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(regex=r'^basic_app/', view=include('basic_app.urls', namespace='basic_app')),
    path('admin/', admin.site.urls),
]

advanced_section/class_based_views/basic_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=500)
    principal = models.CharField(max_length=500)
    location = models.CharField(max_length=500)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Get URL from view/model

        Returns:
            URL
        """
        return reverse(viewname='basic_app:school_create', kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=500)
    age = models.IntegerField()
    # related_name='students' allows us to use {% for student in school_detail.students.all %}
    # in school_detail.html
    school = models.ForeignKey(to=School, on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

advanced_section/class_based_views/basic_app/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy


class IndexView(TemplateView):
    template_name = 'basic_app/index.html'

    def get_context_data(self, **kwargs) -> HttpResponse:
        context = super().get_context_data(**kwargs)
        context['message'] = 'This page uses injected context my means of TempateViews'
        return context


class SchoolListView(ListView):
    # ListView: context variable names
    # ================================
    # By default Django injects "model.School" into context via a list named "school_list" in the
    # HTML template
    # Django lowercases the variable name "School" to "school" and appends "_list" -> "school_list"
    # This variable is a list of all schools in the database
    # We can modify this default behavior by naming the list variable ourselves by using a
    # variable "context_object_name"
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    # DetailView: context varible names
    # =================================
    # Djanog lowercases "models.School" to "school"
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

    # Default template_name generated by Django for "School" CreateView is 'basic_app/school_form.html'
    template_name = 'basic_app/school_create.html'

    # Redirect to this URL after successfully creating a school record
    success_url = reverse_lazy('basic_app:school_list')


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal', 'location')
    model = models.School

    # Default template_name generated by Django for "School" UpdateView (same as for CreateView)
    # is 'basic_app/school_form.html'
    template_name = 'basic_app/school_create.html'


class SchoolDeleteView(DeleteView):
    context_object_name = 'school'
    model = models.School

    # Default template_name generated by Django for "School" DeleteView is 'basic_app/school_confirm_delete.html'
    template_name = 'basic_app/school_confirm_delete.html'

    # Redirect to this URL after successfully deleting a school record
    success_url = reverse_lazy('basic_app:school_list')

advanced_section/class_based_views/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:school_list' %}">List schools</a></li>
        <li><a class="navbar-brand" href="{% url 'basic_app:school_create' %}">Add schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <!--<li><a href="#"></a></li>-->
    </ul>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

advanced_section/class_based_views/basic_app/templates/basic_app/school_confirm_delete.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h2>Delete {{ school.name }}?</h2>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete" >
    <a href="{% url 'basic_app:school_list' %}">Cancel</a>

</form>
{% endblock %}

advanced_section/class_based_views/basic_app/templates/basic_app/school_create.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<h1>
    {% if form.instance.pk %}
    Update School
    {% else %}
    Add School
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
{% endblock %}

advanced_section/class_based_views/basic_app/templates/basic_app/school_detail.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>School Details</h1>
    <p>Name: {{ school_detail.name }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <h3>Students</h3>
    {% for student in school_detail.students.all %}
        <p>Name: {{ student.name }}, Age: {{ student.age }}</p>
    {% endfor %}
</div>
<div class="container">
    <p><a href="{% url 'basic_app:school_update' pk=school_detail.pk %}" class="btn btn-primary">Update</a></p>
    <p><a href="{% url 'basic_app:school_delete' pk=school_detail.pk %}" class="btn btn-primary">Delete</a></p>
</div>
{% endblock %}

advanced_section/class_based_views/basic_app/templates/basic_app/school_list.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>List of Schools</h1>
<ol>
    {% for school in schools %}
    <h3><li><a href="{{ school.id }}">{{ school.name }}</a></li></h3>
    {% endfor %}
</ol>
{% endblock %}

advanced_section/class_based_views/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

advanced_section/class_based_views/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Home Page</h1>
    <p>{{ message }}</p>
</div>
{% endblock %}